name: Update Lookup File

on:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight UTC; adjust as needed
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write     # Grants the workflow write access to repository contents.

jobs:
  update-lookup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or your preferred version

      - name: Install Dependencies
        run: npm install

      - name: List Files in Directory
        run: ls -la

      - name: Update Lookup File
        env:
          RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
          # You can add additional secrets here if needed for Star Atlas queries.
        run: node updateLookup.js

      - name: List Files in Directory
        run: ls -la

      # You can make whatever type of change to the repo...
      - run: echo "123" > ./file.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'Updating lookup file'
          add: '*.txt --force'

      - name: Commit lookup.json changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'Updating lookup file'
          add: 'lookup.json --force'

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main   # Ensure this matches your primary branch
